@startuml

package domain {
    package klausur {
        enum Klausurart {
            ONLINE
            PRAESENZ
        }

        class VeranstaltungsId {
            @Rules
            String id
        }

        class Klausur {
            String fach
            LocalDate datum
            LocalTime von
            LocalTime bis
            Klausurart klausurart
            VeranstaltungsId veranstaltungsId
            LocalTime berechneFreistellungsStartzeitpunkt()
            LocalTime berechneFreistellungsEndzeitpunkt()
        }
    }


    package student {
        class Urlaubstermin {
            LocalDate datum
            LocalTime von
            LocalTime bis
            boolean istVielfacheViertelstunde()
        }
        class Student {
            GithubHandle handle
            Set<KlausurReferenz> klausurtermine
            Set<Urlaubstermin> urlaubstermine
            double berechneResturlaub()
            void fuegeKlausurterminHinzu()
            void fuegeUrlaubsterminHinzu()
        }

        Student --> Urlaubstermin
    }
    student --> klausur

}

package service {
    package studentenservice {
        class StudentService {
            void berechneResturlaub()
            void klausurAnmelden()
            Set<Klausur> klausurtermine()
            void klausurStornieren()
            void urlaubAnmelden()
            Set<Urlaubstermin> urlaubstermine()
            void urlaubStornieren()
        }
    }

    package klausurservice {
        class KlausurService {
            void klausurSpeichern()
            Set<Klausur> alleKlausuren()
        }
        class KlausurVerifizierer {
            LocalDateTime praktikumsStart
            LocalDateTime praktikumsEnde

            boolean istValide(Integer veranstaltungsId)

        }
    }
    package repositories {
        interface KlausurRepository {}
        interface StudentRepository {}
    }
    KlausurService --> KlausurRepository
    StudentService --> StudentRepository
    StudentService --> KlausurRepository

}

package infrastructure {
    class ChickenApplication {}
    package web {
        class KlausurController {}
        class UrlaubsterminController {}
        class StartseitenController {}
    }
    package persistenz {

        package dao {
            interface KlausurDao extends CrudRepository {}
            interface StudentDao extends CrudRepository {}
        }
        class KlausurRepositoryImpl {
            KlausurDao klausurDao
        }
        class StudentRepositoryImpl {
            StudentDao studentDao
        }

        package dto {
          class KlausurDto {
            Long id
            String fach
            LocalDate datum
            LocalTime von
            LocalTime bis
            boolean klausurart
            String veranstaltungsId
          }
          class StudentDto {
            Long id
            String handle
            Set<KlausurReferenz> klausurtermine
            Set<Urlaubstermin> urlaubstermine
          }
        }



        StudentRepositoryImpl --> StudentDao
        KlausurRepositoryImpl --> KlausurDao
        StudentDao --> StudentDto
        KlausurDao --> KlausurDto
    }
}

service --> domain
infrastructure --> service
infrastructure --> domain

@enduml